const ACTIONS = {
  PROJECTS: {
    GET_PROJECTS_DONE: "GET_PROJECTS_DONE",
    GET_PROJECTS_FAILED: "GET_PROJECTS_FAILED",

    CREATE_PROJECT_DONE: "CREATE_PROJECT_DONE",
    CREATE_PROJECT_FAILED: "CREATE_PROJECT_FAILED",

    GET_PROJECT_DONE: "GET_PROJECT_DONE",
    GET_PROJECT_FAILED: "GET_PROJECT_FAILED",

    GET_PROJECT_WITH_TIMESHEET_DONE: "GET_PROJECT_WITH_TIMESHEET_DONE",
    GET_PROJECT_WITH_TIMESHEET_FAILED: "GET_PROJECT_WITH_TIMESHEET_FAILED",
  },
  EMPLOYEES: {
    GET_EMPLOYEES_DONE: "GET_EMPLOYEES_DONE",
    GET_EMPLOYEES_FAILED: "GET_EMPLOYEES_FAILED",
  },
};
export default ACTIONS;
