const ACTIONS = {
  REGISTER: {
    USER_REGISTRATION_PENDING: "USER_REGISTRATION_PENDING",
    USER_REGISTRATION_SUCCESS: "USER_REGISTRATION_SUCCESS",
    USER_REGISTRATION_FAILED: "USER_REGISTRATION_FAILED",
  },
  LOGIN: {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
  },

  LOGOUT: {
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILED: "LOGOUT_FAILED",
  },
  USERS: {
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_ERROR: "GET_USERS_ERROR",
  },

  VACATIONS: {
    GET_VACATION_PENDING: "GET_VACATION_PENDING",
    GET_VACATION_SUCCESS: "GET_VACATION_SUCCESS",
    GET_VACATION_ERROR: "GET_VACATION_ERROR",
  },
  ALERT_MESSAGE: {
    ALERT_SUCCESS: "ALERT_SUCCESS",
    ALERT_ERROR: "ALERT_ERROR",
    CLEAR: "CLEAR",
  },
};
export default ACTIONS;
